### ISSUE TITLE
Failed to compile with Angular 6

### ISSUE THREAD

**Issue by QuentinIcky** [kamiazya/ngx-speech-recognition#100]
Hi, 

I'm trying to test your package, but I get an error when I start the server.

![Capture d’écran 2019-04-04 à 10 03 50](https://user-images.githubusercontent.com/10741567/55539500-10ad9900-56c1-11e9-8aa9-d272c6f61f97.png)

As you can see on the screenshot there are lot of errors, BUT I can still use it (if I make any change) and it works...

**Comment by kamiazya** [comment]
Hi,
Thanks for report issue.

If you are using Angular 6, please use `kamiazya/ngx-speech-recognition@0.2.1`.


The error may be caused by TypeScript version.

The latest version that supports Angular 7 gives such an error because it removes the deprecated `@types/webspeechapi` dependency.

Please let me know if that is not the case.

**Comment by QuentinIcky** [comment]
Hi,

Thanks for your answer. Unfortunately when I try it doesn't work, I get this error :

`npm ERR! code ENOLOCAL
npm ERR! Could not install from "kamiazya/ngx-speech-recognition@0.2.1" as it does not contain a package.json file.`

**Comment by saad141** [comment]
i'm facing the same issue kindly help me

**Comment by kamiazya** [comment]
I published v0.2.2 for this problem.

It was solved by adding `@types/webspeechapi` to peerDependencies.

Thanks for reporting the problem!
