### ISSUE TITLE
Add maxSpeechTimeout

### ISSUE THREAD

**Issue by starman2015** [kamiazya/ngx-speech-recognition#423]
Hi!
Please add maxSpeechTimeout param(ms) at listen().

**Comment by starman2015** [comment]
example,
this.service.listen(5000).pipe(...).subscribe(...);
Where 5000 - 5000 ms after which recognition should be completed.

**Comment by kamiazya** [comment]
@starman2015 
I'm sorry to be late.

It's a good idea because we didn't consider cancellation conditions.

The policy of the library is to make it as a wrapper for the API provided as standard, so we want to make timeout optional.

I also want to be able to provide other options, so what about the API below?

```typescript

interface IOption {
  timeout?: number;
}

class RxSpeechRecognitionService {
  public listen(option?: IOption);
}
```

Thanks.

**Comment by starman2015** [comment]
Well Done!
